"""
Django settings for shiro project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from configurations import Configuration
import ConfigParser
from utils import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class Base(Configuration):

    ROOT_URLCONF = 'shiro.urls'

    ALLOWED_HOSTS = ['*']

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = config.get('default', 'secret_key')


    # Application definition

    BASE_INSTALLED_APPS = [
        'jet.dashboard',
        'jet',
        'reversion',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ]

    DEV_INSTALLED_APPS = [
        'debug_toolbar',
    ]

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'shiro.wsgi.application'

    BASE_MIDDLEWARE_CLASSES = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    DEV_MIDDLEWARE_CLASSES = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    ]

    @property
    def MIDDLEWARE(self):
        """Dynamically creating MIDDLEWARE_CLASSES according to environment."""
        if self.DEBUG:
            return self.BASE_MIDDLEWARE_CLASSES + self.DEV_MIDDLEWARE_CLASSES

        return self.BASE_MIDDLEWARE_CLASSES

    @property
    def INSTALLED_APPS(self):
        """Dynamically creating INSTALLED_APPS according to environment."""
        if self.DEBUG:
            return self.BASE_INSTALLED_APPS + self.DEV_INSTALLED_APPS

        return self.BASE_INSTALLED_APPS


    # Database
    # https://docs.djangoproject.com/en/1.11/ref/settings/#databases

    """
        using utf8 charset because it will occupy 3 bytes only where as utf8mb4 will occupy 4 bytes.
        max length of character is varchar(255) for utf8 for having index, where as varchar(191) for utf8mb4 with index.
        collation is utf8_unicode_ci <case insensitive collation because to avoid duplicates on case.
        transaction isolation level is read committed not repeatable read,
        because get_or_create in a transaction will be effected because repeatable read will lock the transaction.
        storage is InnoDB.
    """

    DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': config.get('databases', 'DATABASE_NAME'),
                'USER': config.get('databases', 'DATABASE_USER'),
                'PASSWORD': config.get('databases', 'DATABASE_PASSWORD'),
                'HOST': config.get('databases', 'DATABASE_HOST'),
                'PORT': config.get('databases', 'DATABASE_PORT'),
                'CONN_MAX_AGE': 60,
                'OPTIONS': {
                    'charset': 'utf8',
                    'init_command': 'SET '
                    'character_set_connection=utf8,'
                    'collation_connection=utf8_unicode_ci'
                }
            }
    }


    # Password validation
    # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/1.11/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'Asia/Kolkata'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.11/howto/static-files/

    STATIC_URL = '/static/'

    STATIC_ROOT = os.path.join(BASE_DIR, "static/")

class Dev(Base):
    """Settings for dev environment."""
    DEBUG = True

    # TEMPLATE_DEBUG = True
    INTERNAL_IPS = ['10.0.2.15', '127.0.0.1', '192.168.10.10']

class Prod(Base):
    """Setting for prod environment."""

    DEBUG = False

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True      
